// COMPLETE GHANA UNIVERSITIES - REFINED SELECTION
export const GHANA_UNIVERSITIES = [
  // ========== PUBLIC UNIVERSITIES ==========
  { id: 'ug', name: 'University of Ghana', shortName: 'UG', location: 'Legon, Accra', type: 'Public', logo: '/logos/ug.png', color: '#006837', founded: 1948 },
  { id: 'knust', name: 'Kwame Nkrumah University of Science and Technology', shortName: 'KNUST', location: 'Kumasi', type: 'Public', logo: '/logos/knust.png', color: '#003087', founded: 1952 },
  { id: 'ucc', name: 'University of Cape Coast', shortName: 'UCC', location: 'Cape Coast', type: 'Public', logo: '/logos/ucc.png', color: '#003366', founded: 1962 },
  { id: 'uds', name: 'University for Development Studies', shortName: 'UDS', location: 'Tamale', type: 'Public', logo: '/logos/uds.png', color: '#8B0000', founded: 1992 },
  { id: 'uew', name: 'University of Education, Winneba', shortName: 'UEW', location: 'Winneba', type: 'Public', logo: '/logos/uew.png', color: '#006400', founded: 1992 },
  { id: 'umat', name: 'University of Mines and Technology', shortName: 'UMaT', location: 'Tarkwa', type: 'Public', logo: '/logos/umat.png', color: '#4B0082', founded: 2004 },
  { id: 'uhas', name: 'University of Health and Allied Sciences', shortName: 'UHAS', location: 'Ho', type: 'Public', logo: '/logos/uhas.png', color: '#006B6B', founded: 2012 },
  { id: 'uenr', name: 'University of Energy and Natural Resources', shortName: 'UENR', location: 'Sunyani', type: 'Public', logo: '/logos/uenr.png', color: '#FF6600', founded: 2011 },
  { id: 'upsa', name: 'University of Professional Studies Accra', shortName: 'UPSA', location: 'Accra', type: 'Public', logo: '/logos/upsa.png', color: '#003380', founded: 1965 },
  { id: 'gimpa', name: 'Ghana Institute of Management & Public Administration', shortName: 'GIMPA', location: 'Greenhill', type: 'Public', logo: '/logos/gimpa.png', color: '#CC0000', founded: 1961 },
  { id: 'gctu', name: 'Ghana Communication Technology University', shortName: 'GCTU', location: 'Accra', type: 'Public', logo: '/logos/gctu.png', color: '#0066CC', founded: 2005 },
  { id: 'rmu', name: 'Regional Maritime University', shortName: 'RMU', location: 'Tema', type: 'Public', logo: '/logos/rmu.png', color: '#006994', founded: 1988 },
  { id: 'uahs', name: 'University of Allied Health Sciences', shortName: 'UAHS', location: 'Ho', type: 'Public', logo: '/logos/uahs.png', color: '#FF6347', founded: 2021 },
  { id: 'gi-deaf', name: 'Ghana Institute of Journalism', shortName: 'GIJ', location: 'Accra', type: 'Public', logo: '/logos/gij.png', color: '#000080', founded: 1951 },
  { id: 'adventist', name: 'Valley View University', shortName: 'VVU', location: 'Oyibi', type: 'Public', logo: '/logos/vvu.png', color: '#003399', founded: 1979 },
  { id: 'sd-dombo', name: 'SD Dombo University of Business & Integrated Dev', shortName: 'SDD-UBIDS', location: 'Navrongo', type: 'Public', logo: '/logos/sdd-ubids.png', color: '#228B22', founded: 2022 },

  // ========== TECHNICAL UNIVERSITIES ==========
  { id: 'ttu', name: 'Takoradi Technical University', shortName: 'TTU', location: 'Takoradi', type: 'Technical', logo: '/logos/ttu.png', color: '#006633', founded: 1951 },
  { id: 'atu', name: 'Accra Technical University', shortName: 'ATU', location: 'Accra', type: 'Technical', logo: '/logos/atu.png', color: '#003399', founded: 1949 },
  { id: 'htu', name: 'Ho Technical University', shortName: 'HTU', location: 'Ho', type: 'Technical', logo: '/logos/hto.png', color: '#009933', founded: 1968 },
  { id: 'kst', name: 'Kumasi Technical University', shortName: 'KsTU', location: 'Kumasi', type: 'Technical', logo: '/logos/kstu.png', color: '#CC6600', founded: 1954 },
  { id: 'btu', name: 'Bolgatanga Technical University', shortName: 'BTU', location: 'Bolgatanga', type: 'Technical', logo: '/logos/btu.png', color: '#660066', founded: 1963 },
  { id: 'watu', name: 'Wa Technical University', shortName: 'WaTU', location: 'Wa', type: 'Technical', logo: '/logos/watu.png', color: '#006666', founded: 1988 },
  { id: 'cctu', name: 'Cape Coast Technical University', shortName: 'CCTU', location: 'Cape Coast', type: 'Technical', logo: '/logos/cctu.png', color: '#990000', founded: 1984 },
  { id: 'ktu', name: 'Koforidua Technical University', shortName: 'KTU', location: 'Koforidua', type: 'Technical', logo: '/logos/ktu.png', color: '#004C97', founded: 1955 },
  { id: 'stu', name: 'Sunyani Technical University', shortName: 'STU', location: 'Sunyani', type: 'Technical', logo: '/logos/stu.png', color: '#336600', founded: 1963 },
  { id: 'tatu', name: 'Tamale Technical University', shortName: 'TaTU', location: 'Tamale', type: 'Technical', logo: '/logos/tatu.png', color: '#228B22', founded: 1963 },
  { id: 'bretec', name: 'Berekum College of Technology', shortName: 'BRECT', location: 'Berekum', type: 'Technical', logo: '/logos/brect.png', color: '#FF1493', founded: 2005 },
  { id: 'kktech', name: 'Kete Krachi Technical University', shortName: 'KKTU', location: 'Kete Krachi', type: 'Technical', logo: '/logos/kktu.png', color: '#20B2AA', founded: 2018 },
  { id: 'kintampo', name: 'Kintampo College of Health & Wellbeing', shortName: 'KCHW', location: 'Kintampo', type: 'Technical', logo: '/logos/kchw.png', color: '#DC143C', founded: 1926 },
  { id: 'tamale-nursing', name: 'Tamale Nursing & Midwifery Training College', shortName: 'TNMTC', location: 'Tamale', type: 'Technical', logo: '/logos/tnmtc.png', color: '#FF69B4', founded: 1958 },
  { id: 'sunyani-nursing', name: 'Sunyani Nursing Training College', shortName: 'SNTC', location: 'Sunyani', type: 'Technical', logo: '/logos/sntc.png', color: '#9370DB', founded: 1945 },
  { id: 'wa-nursing', name: 'Wa Nursing Training College', shortName: 'WNTC', location: 'Wa', type: 'Technical', logo: '/logos/wntc.png', color: '#DDA0DD', founded: 1970 },
  { id: 'ho-nursing', name: 'Ho Nursing Training College', shortName: 'HNTC', location: 'Ho', type: 'Technical', logo: '/logos/hntc.png', color: '#BA55D3', founded: 1963 },
  { id: 'koforidua-nursing', name: 'Koforidua Nursing & Midwifery Training College', shortName: 'KNMTC', location: 'Koforidua', type: 'Technical', logo: '/logos/kntc.png', color: '#8A2BE2', founded: 1957 },
  { id: 'berekum-nursing', name: 'Berekum Holy Family Nursing Training College', shortName: 'BFNTC', location: 'Berekum', type: 'Technical', logo: '/logos/bfntc.png', color: '#FF4500', founded: 2007 },

  // ========== PRIVATE UNIVERSITIES & COLLEGES ==========
  { id: 'ashesi', name: 'Ashesi University', shortName: 'Ashesi', location: 'Berekuso', type: 'Private', logo: '/logos/ashesi.png', color: '#003366', founded: 2002 },
  { id: 'central', name: 'Central University', shortName: 'Central', location: 'Miotso', type: 'Private', logo: '/logos/central.png', color: '#800000', founded: 1988 },
  { id: 'regent', name: 'Regent University College of Science & Technology', shortName: 'Regent', location: 'Dansoman', type: 'Private', logo: '/logos/regent.png', color: '#660033', founded: 2003 },
  { id: 'kaaf', name: 'KAAF University College', shortName: 'KAAF', location: 'Airport', type: 'Private', logo: '/logos/kaaf.png', color: '#003300', founded: 1997 },
  { id: 'lancaster', name: 'Lancaster University Ghana', shortName: 'LUG', location: 'Central Region', type: 'Private', logo: '/logos/lancester.png', color: '#C8102E', founded: 2013 },
  { id: 'radford', name: 'Radford University College', shortName: 'Radford', location: 'Abokobi', type: 'Private', logo: '/logos/radford.png', color: '#DC143C', founded: 2012 },
  { id: 'knutsford', name: 'Knutsford University College', shortName: 'Knutsford', location: 'Accra', type: 'Private', logo: '/logos/knutsford.png', color: '#8B0000', founded: 2003 },
  { id: 'datalink', name: 'Data Link University College', shortName: 'DLI', location: 'Tema', type: 'Private', logo: '/logos/dli.png', color: '#4169E1', founded: 2005 },
  { id: 'familyhealth', name: 'Family Health University College', shortName: 'FHUC', location: 'Teshie', type: 'Private', logo: '/logos/fhuc.png', color: '#FF69B4', founded: 2015 },
  { id: 'webster', name: 'Webster University Ghana', shortName: 'Webster', location: 'East Legon', type: 'Private', logo: '/logos/webster.png', color: '#0033A0', founded: 2015 },
  { id: 'unity', name: 'Unity University College', shortName: 'Unity', location: 'Accra', type: 'Private', logo: '/logos/unity.png', color: '#228B22', founded: 2002 },
  { id: 'dominion', name: 'Dominion University College', shortName: 'Dominion', location: 'Accra', type: 'Private', logo: '/logos/dominion.png', color: '#FFD700', founded: 2007 },
  { id: 'allnations', name: 'All Nations University', shortName: 'ANUC', location: 'Koforidua', type: 'Private', logo: '/logos/anuc.png', color: '#FF4500', founded: 1996 },
  { id: 'christianservice', name: 'Christian Service University College', shortName: 'CSUC', location: 'Kumasi', type: 'Private', logo: '/logos/csuc.png', color: '#4169E1', founded: 1974 },
  { id: 'catholic', name: 'Catholic University College of Ghana', shortName: 'CUCG', location: 'Sunyani', type: 'Private', logo: '/logos/cucg.png', color: '#FFFFFF', founded: 2003 },
  { id: 'mountcrest', name: 'Mountcrest University College', shortName: 'Mountcrest', location: 'Kumasi', type: 'Private', logo: '/logos/mountcrest.png', color: '#8B4513', founded: 2007 },
  { id: 'accrabusiness', name: 'Accra Business School', shortName: 'ABS', location: 'Accra', type: 'Private', logo: '/logos/abs.png', color: '#0066CC', founded: 2004 },
  { id: 'academiccity', name: 'Academic City University College', shortName: 'ACUC', location: 'Accra', type: 'Private', logo: '/logos/acuc.png', color: '#00BFFF', founded: 2015 },
  { id: 'ghanachristian', name: 'Ghana Christian University College', shortName: 'GCUC', location: 'Amrahia', type: 'Private', logo: '/logos/gcuc.png', color: '#D2691E', founded: 2005 },
  { id: 'zenith', name: 'Zenith University College', shortName: 'Zenith', location: 'La', type: 'Private', logo: '/logos/zenith.png', color: '#000066', founded: 2003 },
  { id: 'bluecrest', name: 'BlueCrest University College', shortName: 'BlueCrest', location: 'Accra', type: 'Private', logo: '/logos/bluecrest.png', color: '#0066CC', founded: 2011 },
  { id: 'pentecost', name: 'Pentecost University', shortName: 'PU', location: 'Sowutuom', type: 'Private', logo: '/logos/pu.png', color: '#FF0000', founded: 2007 },
  { id: 'methodist', name: 'Methodist University Ghana', shortName: 'MUG', location: 'Tema', type: 'Private', logo: '/logos/mug.png', color: '#006600', founded: 2000 },
  { id: 'presby', name: 'Presbyterian University College', shortName: 'PUCG', location: 'Abetifi', type: 'Private', logo: '/logos/pucg.png', color: '#003366', founded: 2003 },
  { id: 'ghmedia', name: 'GH Media University College', shortName: 'GH Media', location: 'Accra', type: 'Private', logo: '/logos/ghmedia.png', color: '#FF4500', founded: 2020 },
  { id: 'maranatha', name: 'Maranatha University College', shortName: 'Maranatha', location: 'Accra', type: 'Private', logo: '/logos/maranatha.png', color: '#DC143C', founded: 2006 },
  { id: 'islamic', name: 'Islamic University College Ghana', shortName: 'IUG', location: 'Accra', type: 'Private', logo: '/logos/iug.png', color: '#006600', founded: 1988 },
  { id: 'wisconsin', name: 'Wisconsin International University College', shortName: 'WIUC', location: 'Accra', type: 'Private', logo: '/logos/wiuc.png', color: '#CC0000', founded: 2001 },
  { id: 'ait', name: 'Accra Institute of Technology', shortName: 'AIT', location: 'Accra', type: 'Private', logo: '/logos/ait.png', color: '#003366', founded: 2005 },
  { id: 'spiritan', name: 'Spiritan University College', shortName: 'SUC', location: 'Nsoatre', type: 'Private', logo: '/logos/suc.png', color: '#87CEEB', founded: 2015 },
  { id: 'kings', name: 'Kings University College', shortName: 'KUC', location: 'Accra', type: 'Private', logo: '/logos/kuc.png', color: '#FFD700', founded: 2009 },
  { id: 'trinity', name: 'Trinity Theological Seminary', shortName: 'TTS', location: 'Legon', type: 'Private', logo: '/logos/tts.png', color: '#8B0000', founded: 1942 },
];

export const getUniversityById = (id) => GHANA_UNIVERSITIES.find(u => u.id === id) || GHANA_UNIVERSITIES[GHANA_UNIVERSITIES.length - 1];
